compatibility_date = "2021-11-13"
name = "esbuild-cfw"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true

[build]
command = "yarn install && npm run build"

[build.upload]
format = "service-worker"